name: run-tests
on: [push,pull_request]
jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@master
    with:
      ini-values: date.timezone='UTC'
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1','8.2']